{% set name = "wandb" %}
{% set version = "0.16.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v{{ version }}.tar.gz
  sha256: 938b7dd023a29282b63034d4d383939c1d0f00d3161375994f7a9d9d619bae45


build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script_env: WANDB_BUILD_SKIP_APPLE=true  # [osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go-nocgo') }}
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - appdirs >=1.4.3
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >=3.19.0,!=4.21.0,<5
    - psutil >=5.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=1.0.0
    - setproctitle
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
    - kptkin
    - dmitryduev
    - timoffex
