{% set name = "wandb" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v{{ version }}.tar.gz
  sha256: 8f1c02dcc80ab33f195d1594bc25066d2ca1874e0e221490331fba001af45031

build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - go-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - setuptools
    - typing_extensions
  run:
    - pydantic >=2.6,<3
    - six
    - typing >=3.6.4
    - setuptools
    - python
    - appdirs >=1.4.3
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >=3.19.0,!=4.21.0,!=5.28.0,<6
    - psutil >=5.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=2.0.0
    - setproctitle
    - typing_extensions >=4.4,<5

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
    - python -c "import wandb"
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - kptkin
    - dmitryduev
    - timoffex
